--Comando DDL Sistema de Aluguel de Equipamentos

-- Tabela 1: CLIENTES
CREATE TABLE CLIENTES(
	cliente_id INT IDENTITY(1,1) NOT NULL, 
	Nome VARCHAR(100) NOT NULL, 
	CPF_CNPJ VARCHAR(18) NOT NULL, 
	email VARCHAR(100) NOT NULL, 
	telefone VARCHAR(15) NOT NULL, 
	endereco_id INT NOT NULL,
	CONSTRAINT PK_CLIENTES PRIMARY KEY (cliente_id));

-- Tabela 2: FUNCIONARIOS
CREATE TABLE FUNCIONARIOS(
	funcionario_id INT IDENTITY(1,1) NOT NULL, 
	nome VARCHAR(100) NOT NULL, 
	cargo VARCHAR(50) NOT NULL, 
	dt_contratacao DATE NOT NULL, 
	CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY (funcionario_id),
	-- CONSTRAINT CHECK para data de contratação (Regra de Negócio)
	CONSTRAINT CK_FUNC_CONTRATACAO CHECK (dt_contratacao <= GETDATE()));

-- Tabela 3: ENDERECO
CREATE TABLE ENDERECO(
	endereco_id INT IDENTITY(1,1) NOT NULL, 
	logradouro VARCHAR(100) NOT NULL, 
	bairro VARCHAR(50) NOT NULL, 
	numero VARCHAR(10) NOT NULL, 
	complemento VARCHAR(15) NULL, 
	cidade VARCHAR NOT NULL,
	estado CHAR(2) NOT NULL,
	cep VARCHAR(8) NOT NULL,
	CONSTRAINT PK_ENDERECO PRIMARY KEY (endereco_id));

-- Tabela 4: CATEGORIA
CREATE TABLE CATEGORIA(
	categoria_id INT IDENTITY(1,1) NOT NULL, 
	nome_categoria VARCHAR(50) NOT NULL, 
	descricao VARCHAR(255) NOT NULL, 
	CONSTRAINT PK_CATEGORIA PRIMARY KEY (categoria_id));

-- Tabela 5: EQUIPAMENTO
CREATE TABLE EQUIPAMENTO(
	equipamento_id INT IDENTITY(1,1) NOT NULL, 
	nome VARCHAR(100) NOT NULL, 
	modelo VARCHAR(100) NOT NULL,
	numero_serie VARCHAR(50) NOT NULL,
	preco_diaria DECIMAL(10,2) NOT NULL,
	status VARCHAR(20) NOT NULL, 
	CONSTRAINT PK_EQUIPAMENTO PRIMARY KEY (equipamento_id));
	
-- Adicionando categoria_id na tabela de EQUIPAMENTO
	ALTER TABLE EQUIPAMENTO
	ADD categoria_id INT NOT NULL;

-- Tabela 6: ESTOQUE
CREATE TABLE ESTOQUE(
	estoque_id INT IDENTITY(1,1) NOT NULL, 
	equipamento_id INT NOT NULL, 
	quant_disponivel SMALLINT NOT NULL,
	quant_total SMALLINT NOT NULL,
	data_revisao DATETIME NOT NULL
	CONSTRAINT PK_ESTOQUE PRIMARY KEY (estoque_id),
	-- CONSTRAINT CHECK para integridade de estoque
	CONSTRAINT CK_ESTOQUE_DISP CHECK (quant_disponivel <= quant_total));

-- Tabela 7: ALUGUEL
CREATE TABLE ALUGUEL(
	aluguel_id INT IDENTITY(1,1) NOT NULL, 
	cliente_id INT NOT NULL, 
	funcionario_id INT NOT NULL,
	data_inicio DATETIME NOT NULL,
	data_devolucao DATETIME NULL, -- Null, pois a devolução pode estar pendente
	valor_total DECIMAL(10,2) NOT NULL, 
	CONSTRAINT PK_ALUGUEL PRIMARY KEY (aluguel_id));

-- Tabela 8: ALUGUEL_ITEM (Relacionamento N:N)
CREATE TABLE ALUGUEL_ITEM(
	aluguel_id INT  NOT NULL, 
	equipamento_id INT NOT NULL, 
	quantidade SMALLINT NOT NULL,
	valor_diaria DECIMAL(10,2) NOT NULL, 
	CONSTRAINT PK_ALUGUEL_ITEM PRIMARY KEY (aluguel_id, equipamento_id)); --Chave Primária Composta

-- Tabela 9: PAGAMENTOS
CREATE TABLE PAGAMENTOS(
	pagamento_id INT IDENTITY(1,1)  NOT NULL, 
	aluguel_id INT NOT NULL, 
	valor_pago DECIMAL(10,2) NOT NULL,
	metodo_pagamento VARCHAR(50) NOT NULL, 
	dt_pagamento DATETIME NOT NULL, 
	CONSTRAINT PK_PAGAMENTOS PRIMARY KEY (pagamento_id));

-- Tabela 10: MANUTENCAO
CREATE TABLE MANUTENCAO(
	manutencao_id INT IDENTITY(1,1)  NOT NULL, 
	equipamento_id INT NOT NULL, 
	fornecedor_id INT NOT NULL,  
	dt_inicio DATETIME NOT NULL, 
	dt_final DATETIME NULL, -- Null, pois a manutenção pode estar em andamento
	custo DECIMAL(10,2) NOT NULL, 
	descricao VARCHAR(255) NOT NULL, 
	CONSTRAINT PK_MANUTENCAO PRIMARY KEY (manutencao_id));

-- Tabela 11: MULTAS
CREATE TABLE MULTAS(
	multa_id INT IDENTITY(1,1)  NOT NULL, 
	aluguel_id INT NOT NULL, 
	valor_multa DECIMAL(10,2) NOT NULL,  
	descricao VARCHAR(255) NOT NULL, 
	dt_multa DATETIME NOT NULL,
	status_pagamento VARCHAR(20) NOT NULL, 
	CONSTRAINT PK_MULTAS PRIMARY KEY (multa_id));

-- Tabela 12: FORNECEDORES
CREATE TABLE FORNECEDORES (
	fornecedor_id INT IDENTITY(1,1)  NOT NULL, 
	nome VARCHAR(100) NOT NULL,  
	cnpj CHAR(18) NOT NULL, 
	telefone VARCHAR(15) NOT NULL, 
	CONSTRAINT PK_FORNECEDORES PRIMARY KEY (fornecedor_id));

-- REGRAS DE UNIDADE (UNIQUE)

ALTER TABLE CLIENTES
ADD CONSTRAINT UK_CLIENTE_CPF UNIQUE (CPF_CNPJ);
ALTER TABLE CLIENTES 
ADD CONSTRAINT UK_CLIENTE_EMAIL	UNIQUE (email);

ALTER TABLE CATEGORIA
ADD CONSTRAINT UK_CATEGORIA_NOME UNIQUE (nome_categoria);

ALTER TABLE EQUIPAMENTO
ADD CONSTRAINT UK_EQUIPAMENTO_NUMSERIE UNIQUE (numero_serie);

ALTER TABLE FORNECEDORES
ADD CONSTRAINT UK_FORNECEDORES_CNPJ	UNIQUE (cnpj);

-- CHAVES ESTRANGEIRAS (FOREIGN KEYS)

-- CLIENTES
ALTER TABLE CLIENTES
ADD CONSTRAINT FK_CLIENTE_ENDERECO FOREIGN KEY (endereco_id)
REFERENCES ENDERECO (endereco_id);

-- EQUIPAMENTO
ALTER TABLE EQUIPAMENTO
ADD CONSTRAINT FK_EQUIPAMENTO_CATEGORIA	FOREIGN KEY (categoria_id)
REFERENCES CATEGORIA (categoria_id);

-- ESTOQUE
ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_ESTOQUE_EQUIPAMENTO FOREIGN KEY (equipamento_id)
REFERENCES EQUIPAMENTO (equipamento_id);

-- ALUGUEL
ALTER TABLE ALUGUEL
ADD CONSTRAINT FK_ALUGUEL_CLIENTE FOREIGN KEY (cliente_id)
REFERENCES CLIENTES (cliente_id);
ALTER TABLE ALUGUEL
ADD CONSTRAINT FK_ALUGUEL_FUNCIONARIO FOREIGN KEY (funcionario_id)
REFERENCES FUNCIONARIOS (funcionario_id);

-- ALUGUEL_ITEM
ALTER TABLE ALUGUEL_ITEM
ADD CONSTRAINT FK_ALUGUELITEM_ALUGUEL FOREIGN KEY (aluguel_id)
REFERENCES ALUGUEL (aluguel_id);
ALTER TABLE ALUGUEL_ITEM
ADD CONSTRAINT FK_ALUGUELITEM_EQUIPAMENTO FOREIGN KEY (equipamento_id)
REFERENCES EQUIPAMENTO (equipamento_id);

-- PAGAMENTOS
ALTER TABLE PAGAMENTOS 
ADD CONSTRAINT FK_PAGAMENTOS_ALUGUEL FOREIGN KEY (aluguel_id)
REFERENCES ALUGUEL (aluguel_id);

-- MANUTENCAO
ALTER TABLE MANUTENCAO
ADD CONSTRAINT FK_MANUTENCAO_EQUIP FOREIGN KEY (equipamento_id)
REFERENCES EQUIPAMENTO (equipamento_id);
ALTER TABLE MANUTENCAO
ADD CONSTRAINT FK_MANUTENCAO_FORN	FOREIGN KEY (fornecedor_id)
REFERENCES FORNECEDORES (fornecedor_id);

-- MULTAS
ALTER TABLE MULTAS
ADD CONSTRAINT FK_MULTAS_ALUGUEL FOREIGN KEY (aluguel_id)
REFERENCES ALUGUEL (aluguel_id);

--
